pushd "Pycckuu__Tatiana 2.30"
"C:\Program Files (x86)\GMapTool\gmt\gmt.exe" -j -v -a -b 1 -c 2.39,0,006-D4896-00 -m tatiana -o "..\..\dist\Pycckuu__Tatiana 2.30\Pycckuu__Tatiana.vpm" -q -x DLLINFO.TXT BRKINF22.HDR CLM_RUR.DAT DPS_RUR.DAT DPS_MIL.DAT PHM_MIL.DAT PP_RUR.DAT SDCT_RUR.DAT SN22_MIL.DAT SYNM_F16.DAT TTN_RUR.DAT UDCT_RUR.DAT US_MIL.DAT DLLIMG.BIN GRAM.VXM VAR.VXM DFLT.DCT APDB_TP.DAT APDB.DAT AMILGA22.DAT RULESET.TXT RP_RSET.TXT WORDS.TXT PHRASES.TXT AU.DCT BR.DCT CA.DCT CN.DCT DED.DCT DNK.DCT ES.DCT FI.DCT FR.DCT GB.DCT GR.DCT ID.DCT IN.DCT IT.DCT MY.DCT MX.DCT NL.DCT NO.DCT PL.DCT PT.DCT RU.DCT SE.DCT SG.DCT TH.DCT TW.DCT US.DCT IMGEND.TST
popd
pushd "..\dist\Pycckuu__Tatiana 2.30"
"C:\Program Files (x86)\GMapTool\gmt\gmt.exe" -i -v Pycckuu__Tatiana.vpm >Pycckuu__Tatiana.txt
popd
pause
